version: "2.2"
services:
  web:
    build: .
    container_name: app
    command: bin/rails server --port 3000 --binding 0.0.0.0
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    env_file:
       - .env
